development:
  clients:
    default:
      database: multiple_complexy_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: multiple_complexy_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: multiple_complexy_production
      hosts:
        - localhost:27017
